# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Woodknight.PixelScope
PackageVersion: 0.1.0
InstallerType: zip
NestedInstallerType: portable
ReleaseDate: 2026-04-10
Commands:
- pixelscope
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/woodknight/pixel-scope/releases/download/v0.1.0/pixelscope-0.1.0-windows-x86_64.zip
  InstallerSha256: CE6A402CF24378E0914668CC523C45917F55F86568B2BFDDFA8AECA4D62271EE
  NestedInstallerFiles:
  - RelativeFilePath: PixelScope-0.1.0-Windows-AMD64/bin/pixelscope.exe
    PortableCommandAlias: pixelscope
ManifestType: installer
ManifestVersion: 1.12.0
