#!/bin/sh
HERE="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
export SDL_VIDEO_X11_WMCLASS=pixelscope
export SDL_VIDEO_WAYLAND_WMCLASS=pixelscope
export SDL_APP_NAME=PixelScope
exec "$HERE/usr/bin/pixelscope" "$@"
